services:
  - type: web
    name: host-rate-lumitar
    env: java
    plan: free
    buildCommand: mvn clean package
    startCommand: java -jar target/clickhouse-rate-limiter-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
